export const GET_ALL_VIDEOGAMES = 'GET_ALL_VIDEOGAMES'; 
export const GET_GENRES = 'GET_GENRES'; 
export const GET_VIDEOGAMES_DETAILS = 'GET_VIDEOGAMES_DETAILS'; 
export const DELETE_STATE = 'DELETE_STATE';
